dist: trusty
sudo: false
language: php
php: 
  - '5.6'
addons:
    github_token:
      secure: $GITHUB_TOKEN

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
  - COMPOSER_ARGS="--no-interaction"

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

script:
  - composer cs-check
  
before_deploy:
  - bash .bin/generate-release-package.sh $TRAVIS_TAG
  - ls -lah target

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: target/wpp-integration-demo-php-$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    repo: wirecard/wpp-integration-demo-php
    tags: true
